CLASS zbp_i_bookingsuppl_2860 DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zi_travel_2860.
protected section.
private section.
ENDCLASS.



CLASS ZBP_I_BOOKINGSUPPL_2860 IMPLEMENTATION.
ENDCLASS.
